AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: AWS SAM template for the Stedi::Transfer::Profile resource type

Globals:
  Function:
    Timeout: 180  # docker start-up times can be long for SAM CLI
    MemorySize: 256

Resources:
  TypeFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.stedi.transfer.profile.HandlerWrapper::handleRequest
      Runtime: java11
      CodeUri: ./target/stedi-transfer-profile-handler-1.0-SNAPSHOT.jar

  TestEntrypoint:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.stedi.transfer.profile.HandlerWrapper::testEntrypoint
      Runtime: java11
      CodeUri: ./target/stedi-transfer-profile-handler-1.0-SNAPSHOT.jar

